export function officialStep(label: string) {
  return /captcha|assessment|aptitude|identity|passport copy|national id|privacy|consent|terms|ai use statement|not be ai.generated|configure|unsupported portal|cannot verify/i.test(label);
}
export function prohibitsAnswerDrafting(text: string) {
  return /not be ai[- ]generated|(?:must|should) not (?:use|be generated by) (?:ai|artificial intelligence)|no ai[- ]generated|reflect your own (?:ideas|thinking).*personal experiences/i.test(text);
}
export function draftableQuestions(questions: string[]) {
  return [...new Set(questions)].filter(question => !officialStep(question)).slice(0, 20);
}
