import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { AppShell } from "@/components/dashboard/app-shell";
import { createSupabaseServerClient, getCurrentUser } from "@/lib/supabase/server";
export default async function JobDeskReport({ params }: { params: Promise<{ orderId: string }> }) {
  const user = await getCurrentUser(); if (!user) redirect("/login");
  const db = await createSupabaseServerClient();
  const { data: account } = await db.from("users").select("role").eq("id", user.id).single();
  if (!account || !["admin", "super_admin"].includes(account.role)) redirect("/dashboard");
  const { orderId } = await params;
  const [{ data: order }, { data: matches }] = await Promise.all([db.from("job_desk_orders").select("id,status,client:job_desk_clients(full_name,email)").eq("id", orderId).single(), db.from("job_desk_matches").select("id,score,status,authorized_at,submitted_at,vacancy:job_desk_vacancies(title,company_name,apply_url),application:job_desk_applications(status,provider_message_id,provider_response,error_message)").eq("order_id", orderId).order("score", { ascending: false })]);
  if (!order) notFound();
  const client = Array.isArray(order.client) ? order.client[0] : order.client;
  return <AppShell email={user.email} isAdmin><Link href={`/dashboard/admin/job-desk/${orderId}`} className="text-sm font-bold text-brand-blue">Back to order</Link><h1 className="mt-3 text-3xl font-black">Application report</h1><p className="mt-2 text-sm">{client?.full_name} · Generated {new Date().toLocaleString()}</p><p className="mt-2 text-sm text-black/60 dark:text-white/60">Submission is confirmed only when an email provider ID or an administrator-recorded employer confirmation is shown. Portal applications require human follow-up.</p><div className="mt-7 divide-y divide-black/10 dark:divide-white/10">{matches?.map((match) => { const vacancy = Array.isArray(match.vacancy) ? match.vacancy[0] : match.vacancy; const application = Array.isArray(match.application) ? match.application[0] : match.application; const confirmation = (application?.provider_response as { confirmation?: string } | null)?.confirmation; return <div key={match.id} className="py-5"><a href={vacancy?.apply_url} target="_blank" rel="noopener noreferrer" className="font-bold text-brand-blue">{vacancy?.title} · {vacancy?.company_name}</a><p className="mt-1 text-sm">Match {match.score}% · {match.status.replaceAll("_", " ")}</p><p className="mt-1 text-sm">Authorized: {match.authorized_at ? new Date(match.authorized_at).toLocaleString() : "No"} · Submitted: {match.submitted_at ? new Date(match.submitted_at).toLocaleString() : "No"}</p>{application?.provider_message_id ? <p className="mt-1 text-sm">Email provider confirmation: {application.provider_message_id}</p> : null}{confirmation ? <p className="mt-1 text-sm">Employer confirmation recorded by admin: {confirmation}</p> : null}{application?.error_message ? <p className="mt-1 text-sm">Action required: {application.error_message}</p> : null}</div>; })}{!matches?.length ? <p className="py-6 text-sm">No job matches have been recorded.</p> : null}</div></AppShell>;
}
